# Generated by Django 5.1.5 on 2025-01-29 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('manager_first_name', models.CharField(max_length=255)),
                ('manager_last_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('region', models.CharField(choices=[('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao'), ('Region XIII', 'Caraga')], max_length=100)),
                ('city', models.CharField(choices=[('Zamboanga City', 'Zamboanga City'), ('Dipolog City', 'Dipolog City'), ('Pagadian City', 'Pagadian City'), ('Isabela City', 'Isabela City'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan City', 'Iligan City'), ('Malaybalay City', 'Malaybalay City'), ('Valencia City', 'Valencia City'), ('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City'), ('Mati City', 'Mati City'), ('General Santos', 'General Santos'), ('Koronadal City', 'Koronadal City'), ('Tacurong City', 'Tacurong City'), ('Kidapawan City', 'Kidapawan City'), ('Cotabato City', 'Cotabato City'), ('Marawi City', 'Marawi City'), ('Jolo', 'Jolo'), ('Bongao', 'Bongao'), ('Butuan City', 'Butuan City'), ('Surigao City', 'Surigao City'), ('Tandag City', 'Tandag City'), ('Bayugan City', 'Bayugan City')], max_length=100)),
                ('barangay', models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas')], max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Driver', 'Driver'), ('Inventory Clerk', 'Inventory Clerk'), ('Cashier', 'Cashier'), ('Delivery Assistant', 'Delivery Assistant')], max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(choices=[('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao'), ('Region XIII', 'Caraga')], max_length=100)),
                ('city', models.CharField(choices=[('Zamboanga City', 'Zamboanga City'), ('Dipolog City', 'Dipolog City'), ('Pagadian City', 'Pagadian City'), ('Isabela City', 'Isabela City'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan City', 'Iligan City'), ('Malaybalay City', 'Malaybalay City'), ('Valencia City', 'Valencia City'), ('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City'), ('Mati City', 'Mati City'), ('General Santos', 'General Santos'), ('Koronadal City', 'Koronadal City'), ('Tacurong City', 'Tacurong City'), ('Kidapawan City', 'Kidapawan City'), ('Cotabato City', 'Cotabato City'), ('Marawi City', 'Marawi City'), ('Jolo', 'Jolo'), ('Bongao', 'Bongao'), ('Butuan City', 'Butuan City'), ('Surigao City', 'Surigao City'), ('Tandag City', 'Tandag City'), ('Bayugan City', 'Bayugan City')], max_length=100)),
                ('barangay', models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas')], max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('stock_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uom', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.supplier')),
            ],
        ),
    ]
