# Generated by Django 5.1.4 on 2025-02-15 19:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('manager_first_name', models.CharField(max_length=255)),
                ('manager_last_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('region', models.CharField(choices=[('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao'), ('Region XIII', 'Caraga')], max_length=100)),
                ('city', models.CharField(choices=[('Zamboanga City', 'Zamboanga City'), ('Dipolog City', 'Dipolog City'), ('Pagadian City', 'Pagadian City'), ('Isabela City', 'Isabela City'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan City', 'Iligan City'), ('Malaybalay City', 'Malaybalay City'), ('Valencia City', 'Valencia City'), ('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City'), ('Mati City', 'Mati City'), ('General Santos', 'General Santos'), ('Koronadal City', 'Koronadal City'), ('Tacurong City', 'Tacurong City'), ('Kidapawan City', 'Kidapawan City'), ('Cotabato City', 'Cotabato City'), ('Marawi City', 'Marawi City'), ('Jolo', 'Jolo'), ('Bongao', 'Bongao'), ('Butuan City', 'Butuan City'), ('Surigao City', 'Surigao City'), ('Tandag City', 'Tandag City'), ('Bayugan City', 'Bayugan City')], max_length=100)),
                ('barangay', models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas'), ('Biasong', 'Biasong'), ('Minaog', 'Minaog'), ('Olingan', 'Olingan'), ('Balangasan', 'Balangasan'), ('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Hinaplanon', 'Hinaplanon'), ('Tubod', 'Tubod'), ('Pala-o', 'Pala-o'), ('Bangon', 'Bangon'), ('Lilod', 'Lilod'), ('Basak Malutlut', 'Basak Malutlut'), ('Rosary Heights', 'Rosary Heights'), ('Poblacion', 'Poblacion'), ('Tamontaka', 'Tamontaka'), ('Doongan', 'Doongan'), ('Limaha', 'Limaha'), ('Ampayon', 'Ampayon'), ('Luna', 'Luna'), ('San Juan', 'San Juan'), ('Taft', 'Taft')], max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Driver', 'Driver'), ('Inventory Clerk', 'Inventory Clerk'), ('Cashier', 'Cashier'), ('Delivery Assistant', 'Delivery Assistant')], max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(choices=[('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao'), ('Region XIII', 'Caraga')], max_length=100)),
                ('city', models.CharField(choices=[('Zamboanga City', 'Zamboanga City'), ('Dipolog City', 'Dipolog City'), ('Pagadian City', 'Pagadian City'), ('Isabela City', 'Isabela City'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan City', 'Iligan City'), ('Malaybalay City', 'Malaybalay City'), ('Valencia City', 'Valencia City'), ('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City'), ('Mati City', 'Mati City'), ('General Santos', 'General Santos'), ('Koronadal City', 'Koronadal City'), ('Tacurong City', 'Tacurong City'), ('Kidapawan City', 'Kidapawan City'), ('Cotabato City', 'Cotabato City'), ('Marawi City', 'Marawi City'), ('Jolo', 'Jolo'), ('Bongao', 'Bongao'), ('Butuan City', 'Butuan City'), ('Surigao City', 'Surigao City'), ('Tandag City', 'Tandag City'), ('Bayugan City', 'Bayugan City')], max_length=100)),
                ('barangay', models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas'), ('Biasong', 'Biasong'), ('Minaog', 'Minaog'), ('Olingan', 'Olingan'), ('Balangasan', 'Balangasan'), ('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Hinaplanon', 'Hinaplanon'), ('Tubod', 'Tubod'), ('Pala-o', 'Pala-o'), ('Bangon', 'Bangon'), ('Lilod', 'Lilod'), ('Basak Malutlut', 'Basak Malutlut'), ('Rosary Heights', 'Rosary Heights'), ('Poblacion', 'Poblacion'), ('Tamontaka', 'Tamontaka'), ('Doongan', 'Doongan'), ('Limaha', 'Limaha'), ('Ampayon', 'Ampayon'), ('Luna', 'Luna'), ('San Juan', 'San Juan'), ('Taft', 'Taft')], max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('stock_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uom', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.supplier')),
            ],
        ),
    ]
