# Generated by Django 5.1.4 on 2025-04-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'managed': False},
        ),
    ]
