# Generated by Django 5.1.4 on 2025-02-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='barangay',
            field=models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas'), ('Biasong', 'Biasong'), ('Minaog', 'Minaog'), ('Olingan', 'Olingan'), ('Balangasan', 'Balangasan'), ('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Hinaplanon', 'Hinaplanon'), ('Tubod', 'Tubod'), ('Pala-o', 'Pala-o'), ('Bangon', 'Bangon'), ('Lilod', 'Lilod'), ('Basak Malutlut', 'Basak Malutlut'), ('Rosary Heights', 'Rosary Heights'), ('Poblacion', 'Poblacion'), ('Tamontaka', 'Tamontaka'), ('Doongan', 'Doongan'), ('Limaha', 'Limaha'), ('Ampayon', 'Ampayon'), ('Luna', 'Luna'), ('San Juan', 'San Juan'), ('Taft', 'Taft')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='barangay',
            field=models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas'), ('Biasong', 'Biasong'), ('Minaog', 'Minaog'), ('Olingan', 'Olingan'), ('Balangasan', 'Balangasan'), ('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Hinaplanon', 'Hinaplanon'), ('Tubod', 'Tubod'), ('Pala-o', 'Pala-o'), ('Bangon', 'Bangon'), ('Lilod', 'Lilod'), ('Basak Malutlut', 'Basak Malutlut'), ('Rosary Heights', 'Rosary Heights'), ('Poblacion', 'Poblacion'), ('Tamontaka', 'Tamontaka'), ('Doongan', 'Doongan'), ('Limaha', 'Limaha'), ('Ampayon', 'Ampayon'), ('Luna', 'Luna'), ('San Juan', 'San Juan'), ('Taft', 'Taft')], max_length=100),
        ),
    ]
