# Generated by Django 5.1.4 on 2025-04-08 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordered_by',
            field=models.ForeignKey(blank=True, db_column='ordered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.staffprofile'),
        ),
    ]
