# Generated by Django 5.1.4 on 2025-04-07 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInRecord',
            fields=[
                ('stockin_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.inventoryitem')),
                ('stocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.staffprofile')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.supplier')),
            ],
            options={
                'db_table': 'stockin_records',
                'managed': True,
            },
        ),
    ]
