# Generated by Django 5.1.4 on 2025-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_salesorder_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
