# Generated by Django 5.1.4 on 2025-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
