# Generated by Django 5.1.4 on 2025-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_purchaseorder_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
