# Generated by Django 5.1.4 on 2025-02-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customer_is_active_alter_customer_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
