# Generated by Django 5.1.4 on 2025-04-01 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_delivery_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
        migrations.AddField(
            model_name='delivery',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_id',
            field=models.CharField(default='TEMP', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='management.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. +63 9XXXXXXXXX or 09XXXXXXXXX).', regex='^(?:\\+63 ?9\\d{2} ?\\d{3} ?\\d{4}|09\\d{9})$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.staffprofile'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='contact',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. +63 9XXXXXXXXX or 09XXXXXXXXX).', regex='^(?:\\+63 ?9\\d{2} ?\\d{3} ?\\d{4}|09\\d{9})$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_no',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. +63 9XXXXXXXXX or 09XXXXXXXXX).', regex='^(?:\\+63 ?9\\d{2} ?\\d{3} ?\\d{4}|09\\d{9})$')]),
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='deliveries',
        ),
    ]
