# Generated by Django 5.1.4 on 2025-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='barangay',
            field=models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas'), ('Biasong', 'Biasong'), ('Minaog', 'Minaog'), ('Olingan', 'Olingan'), ('Balangasan', 'Balangasan'), ('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Hinaplanon', 'Hinaplanon'), ('Tubod', 'Tubod'), ('Pala-o', 'Pala-o'), ('Bangon', 'Bangon'), ('Lilod', 'Lilod'), ('Basak Malutlut', 'Basak Malutlut'), ('Rosary Heights', 'Rosary Heights'), ('Poblacion', 'Poblacion'), ('Tamontaka', 'Tamontaka'), ('Doongan', 'Doongan'), ('Limaha', 'Limaha'), ('Ampayon', 'Ampayon'), ('Luna', 'Luna'), ('San Juan', 'San Juan'), ('Taft', 'Taft'), ('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Mabini', 'Mabini')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Zamboanga City', 'Zamboanga City'), ('Dipolog City', 'Dipolog City'), ('Pagadian City', 'Pagadian City'), ('Isabela City', 'Isabela City'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan City', 'Iligan City'), ('Malaybalay City', 'Malaybalay City'), ('Valencia City', 'Valencia City'), ('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City'), ('Mati City', 'Mati City'), ('General Santos', 'General Santos'), ('Koronadal City', 'Koronadal City'), ('Tacurong City', 'Tacurong City'), ('Kidapawan City', 'Kidapawan City'), ('Cotabato City', 'Cotabato City'), ('Marawi City', 'Marawi City'), ('Jolo', 'Jolo'), ('Bongao', 'Bongao'), ('Butuan City', 'Butuan City'), ('Surigao City', 'Surigao City'), ('Tandag City', 'Tandag City'), ('Bayugan City', 'Bayugan City'), ('Koronadal', 'Koronadal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='barangay',
            field=models.CharField(choices=[('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Kauswagan', 'Kauswagan'), ('Macasandig', 'Macasandig'), ('Buhangin', 'Buhangin'), ('Toril', 'Toril'), ('Talomo', 'Talomo'), ('Agdao', 'Agdao'), ('Lagao', 'Lagao'), ('Bula', 'Bula'), ('City Heights', 'City Heights'), ('Dadiangas', 'Dadiangas'), ('Biasong', 'Biasong'), ('Minaog', 'Minaog'), ('Olingan', 'Olingan'), ('Balangasan', 'Balangasan'), ('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Hinaplanon', 'Hinaplanon'), ('Tubod', 'Tubod'), ('Pala-o', 'Pala-o'), ('Bangon', 'Bangon'), ('Lilod', 'Lilod'), ('Basak Malutlut', 'Basak Malutlut'), ('Rosary Heights', 'Rosary Heights'), ('Poblacion', 'Poblacion'), ('Tamontaka', 'Tamontaka'), ('Doongan', 'Doongan'), ('Limaha', 'Limaha'), ('Ampayon', 'Ampayon'), ('Luna', 'Luna'), ('San Juan', 'San Juan'), ('Taft', 'Taft'), ('Pasonanca', 'Pasonanca'), ('Tetuan', 'Tetuan'), ('Santa Maria', 'Santa Maria'), ('Guiwan', 'Guiwan'), ('Mabini', 'Mabini')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(choices=[('Zamboanga City', 'Zamboanga City'), ('Dipolog City', 'Dipolog City'), ('Pagadian City', 'Pagadian City'), ('Isabela City', 'Isabela City'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan City', 'Iligan City'), ('Malaybalay City', 'Malaybalay City'), ('Valencia City', 'Valencia City'), ('Davao City', 'Davao City'), ('Tagum City', 'Tagum City'), ('Panabo City', 'Panabo City'), ('Mati City', 'Mati City'), ('General Santos', 'General Santos'), ('Koronadal City', 'Koronadal City'), ('Tacurong City', 'Tacurong City'), ('Kidapawan City', 'Kidapawan City'), ('Cotabato City', 'Cotabato City'), ('Marawi City', 'Marawi City'), ('Jolo', 'Jolo'), ('Bongao', 'Bongao'), ('Butuan City', 'Butuan City'), ('Surigao City', 'Surigao City'), ('Tandag City', 'Tandag City'), ('Bayugan City', 'Bayugan City'), ('Koronadal', 'Koronadal')], max_length=100),
        ),
    ]
