# Generated by Django 5.1.4 on 2025-05-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_update_vehicles_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='management.staffprofile')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year_manufactured', models.IntegerField()),
                ('type', models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('Motorcycle', 'Motorcycle')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired')], default='Active', max_length=20)),
                ('date_acquired', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField()),
                ('registration_expiry', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'Driver', 'status': 'Active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='management.staffprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vehicles', to='management.staffprofile')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['vehicle_id'],
            },
        ),
    ]
