# Generated by Django 5.1.4 on 2025-05-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_category_expense_vehicle'),
        ('management', '0009_purchaseorderitem_checked_quantity_and_more'),
    ]

    operations = [
    ]
