# Generated by Django 5.1.4 on 2025-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_merge_20250518_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
